# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

default: &dockersettings
  docker:
    - image: amazon/aws-cli

jobs:
  create_infrastructure:
    <<: *dockersettings
    steps:
      command: aws cloudformation create-stack --stack-name CICDImpl --template-file template.yml
  
workflows:
  CICDImpl:
    jobs:
      - create_infrastructure

